modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="powergridtweaks"
version="0.0.8"
displayName="Power Grid Tweaks"
authors="Rerit"
description='''Small tweaks and additions for Create: Power Grid.'''

[[mixins]]
config="powergridtweaks.mixins.json"

[[dependencies.powergridtweaks]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.powergridtweaks]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.powergridtweaks]]
modId="create"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.powergridtweaks]]
modId="architectury"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.powergridtweaks]]
modId="powergrid"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.powergridtweaks]]
modId="ponder"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.powergridtweaks]]
modId="flywheel"
type="required"
versionRange="[1.0.6,)"
ordering="NONE"
side="BOTH"
